### ISSUE TITLE
Compass in titlebar

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/MineInAbyss#115]
Basically ~~copy~~ get inspired by Origin Realms' top bar that has an icon arrow pointing to where you need to go + some extra objective text.

I'd like this to be done via a component that defines a location to point to as well as said objective text. We could then build another system for selecting quests or something like that really easily by updating this component.

Consider how this would work between sections. Finally, perhaps when parsing location we could calculate the depth and include it in the title as well.

**Comment by Derongan** [comment]
Could you provide an example of what this looks like?

**Comment by 0ffz** [comment]
Easiest way is to join their server and see for yourself, I don't have any gifs or images rn sadly.

**Comment by Boy0000** [comment]
Think for cross-section it would just show a dot.
So the compass will display the arrow if ur in the correct section, if not its a dot.
Seeing as it would be a 2D element we cant show down/up in any other way so.

Getting a basic implementation for this shouldnt be too bad.
The quest integration would ofc not be done yet
