### ISSUE TITLE
Locking Armour Stands

### ISSUE THREAD

**Issue by khaazz** [MineInAbyss/MineInAbyss#118]
### Is your feature request related to a problem?

I would like to be able to lock and armour stand so that other players cannot take items from them or destroy them

### Describe the solution you'd like.

The ability to use a command to set and armour stand to only be accessible by the one using the command, possibly with the ability to add other players. This command would make it so that only the players set to that armour stand can interact with it.

### Describe alternatives you've considered.

Alternatively they could somehow be added to the items that can be privated with signs, however I do not know how that would work with their physics

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have ensured the feature I'm requesting isn't already in the latest supported Paper build.

**Comment by Boy0000** [comment]
Could probably just check what player tries to interact with an armorstand.
If it isnt the same as the "owner" cancel the ArmorStandTakeEvent or whatever.
Might be done via a component on placed armorstands that keeps a "owner" perhaps

**Comment by Derongan** [comment]
Interesting that blocklocker doesn't support this use case
