### ISSUE TITLE
Enchantment that collects drops

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/MineInAbyss#133]
### Enchantment name

Magnetism

### Enchantment Info

Magnetism would instantly collect ores and other items when you mine.
Would be able to be applied to pickaxes.

Would only have 1 level as effect would not really differ

### Obtainability

- [X] Enchanted Books
- [ ] Enchantment Table (Randomly applied)
- [X] Vendor Trades
- [ ] Dungeon Loot
- [ ] Other (Details in Additional Info)

### Agreements

- [X] I have searched for and ensured there isn't already an open suggestion similar to this.
- [X] I have ensured the mob I'm suggesting isn't already on the server.

**Comment by c-sig** [comment]
i dont know how to self assign myself but i hereby assign myself to this coding task of non-epic proportions

**Comment by Boy0000** [comment]
Seeing as HiddenOre can drop items outside of spawning it as an ore, this might be abit trickier.
Solution is probably on blockbreak to see if there are any items there.

If so apply the same effect as with normal block breaks for ores, aka collecting them into the inv if theres space
