### ISSUE TITLE
Locked armorstands can be moved

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/MineInAbyss#134]
Either by pistons, fishing rods or by breaking the block beneath them (gravity)

In theory you would want pistons and gravity to be fully cancelled, and fishing rods only affect them if theyre allowed to interact with the armorstand

**Comment by Bloeckchengrafik** [comment]
Working on it over at [Bloeckchengrafik/really_locked_armorstands](https://github.com/Bloeckchengrafik/MineInAbyss/tree/really_locked_armorstands)
