### ISSUE TITLE
Separate Curse into new Plugin

### ISSUE THREAD

**Issue by Derongan** [MineInAbyss/MineInAbyss#14]
Currently the curse is bundled into this main plugin. It would be much easier to manage if it was a separate plugin providing its own API/events. It could depend on deeper world for regions, or perhaps we should migrate both to use WorldGuard regions.

**Comment by Banbeucmas** [comment]
Do you want for it to work independently when we seperate it or still use the main plugin as a dependency?

**Comment by 0ffz** [comment]
I'd like to hold off on this even with the curse rework around the corner so we don't get distracted by cleaning things. In the future, it may be beneficial to others to make an API for giving effects to players, but keeping the application of those effects to those plugins.

So the API would contain cool effects, but we will apply them as the curse in this plugin.

**Comment by 0ffz** [comment]
I think it makes sense to leave curse here for the foreseeable future.
