### ISSUE TITLE
Ender Pearls not correctly handling curse

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/MineInAbyss#144]
Seems that Ender Pearls dont handle curse correctly when the pearl lands ontop of a block.
On the side it seems to work due to you being pushed through the block and therefore moving.

Might simply be that it doesnt trigger handleCurse for this reason

**Comment by desmont323** [comment]
cant recreate the issue for me even if the pear land on top of the block the curse trigger

**Comment by Boy0000** [comment]
It did seem abit odd and inconsistent when i tried it. The check should also not fail
I'll double check and close the issue if I cant reproduce it consistently either.

Otherwise I'll give you a more detailed explanation. Feel free to pick another issue in the meantime 👍

**Comment by desmont323** [comment]
ok all good
