### ISSUE TITLE
Backpacks can be placed via dispensers

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/MineInAbyss#145]
### Expected behavior

Backpacks should not be placable

### Observed/Actual behavior

Backpacks are for now just shulkers, so dispensers can place them

### Steps/models to reproduce

Put a backpack in a dispenser and fire it

### Other

Seems to be easily handled via [this](https://papermc.io/javadocs/paper/1.17/org/bukkit/event/block/BlockDispenseEvent.html). Could just cancel it but it should rather drop the item

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I have made a detailed description of the bug so that it can be reproduced.

**Comment by desmont323** [comment]
i can try to start on that XD
