### ISSUE TITLE
Depth Meter

### ISSUE THREAD

**Issue by Derongan** [MineInAbyss/MineInAbyss#15]
Currently we don't have a way to tell how deep a block is

It would need to leverage both DeeperWorld and the known layer depths. Using this we can convert minecraft depth -> abyss depth

**Comment by Banbeucmas** [comment]
From my understanding (with Offz explaination a bit). You guys divided the world into sections which overlap each other right? Correct me if I am wrong. I don't understand yet with what would happen on how the plugin would do with the last section of the world (Presumably bottom one) and the first one on the top of the world. 

Might need some explaination on that. Would those 2 section have some overlap part or not?

**Comment by Derongan** [comment]
@Banbeucmas Here is a graphic representing how it works. What you said sounds about right. For the bottom and top there are no sections above or below defined in config so it just doesn't teleport.

The reason this is under MineInAbyss not DeeperWorld is due to its general specificity. This counter would only really work in our server.

We have a defined start of layer one. We can define this as 0 meters. This continues down to a defined start of layer 2. This would be the official depth of layer one according to the manga. Overlap only matters because you shouldnt count it twice. Its pretty easy with these two points to figure out how many blocks it is (if its 5 sections its 256*5 - the overlap per adjacent sections) and then figure out how many minecraft blocks are equivilant to one real abyss meter.

![mine in abyss](https://user-images.githubusercontent.com/1530104/51791811-e4741a00-215d-11e9-95da-30f3887de784.png)

**Comment by Derongan** [comment]
This is in the latest version, but configs need to be updated

**Comment by Boy0000** [comment]
Right now it seems to calculate depth for the entire layer on each section instead of for each section by itself. Meaning that the depth it shows for a y-value is wrong on each section. It also calculates depth weirdly as each block you go down increases it by different amounts, probably due to rounding up.
![image](https://user-images.githubusercontent.com/62521371/119503890-b9b92100-bd6b-11eb-8bd7-96e25fbd01d7.png)

**Comment by Derongan** [comment]
The not 1:1 is intentional I think. If this is using my old systems ported over to the current ecs, the depth is based on manga depth.

**Comment by 0ffz** [comment]
Maybe an absolute y value might be useful to survival people that want accuracy but honestly the depth is still consistent based on your location in the world. You can always tell someone to meet at x meters deep and they will be able to find that with the compass. That seems good enough for me

**Comment by Boy0000** [comment]
The fact that it takes canon height instead of ingame height works fine (sectionchanges make it scuffy anyway)
Only thing that is wrong then is that it shows depth per section, not per layer (?)
