### ISSUE TITLE
Orth currency and exp

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/MineInAbyss#23]
Use something (maybe Vault?) to store currency that can be used in Orth.

If a player dies in the abyss, some calculation should be done to reward them with currency to use back in Orth.

Perhaps it's better to add this currency as the player explores the abyss, e.x. for reaching a certain layer, killing mobs, getting relics...

Lastly, we should consider a leveling system with exp gained by playing that could be displayed next to the player's name. It could also be derived from the lifetime currency collected by a player. A certain level could also be required for getting a whistle upgrade.

**Comment by Anthropomorphed** [comment]
Adding a way to hide your "experience/level" after a certain criteria has been reached would be nice.
Being able to hide your status or even your name could lead to interesting outcomes.

I can see the problem if everyone could do it, that's why the criteria shouldn't be accessable that easy

**Comment by 0ffz** [comment]
Outdated
