### ISSUE TITLE
Curse Stacking

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/MineInAbyss#31]
Curse stacking would be a simple true/false option for each effect in the config, which would check whether an existing effect of the same type has been applied, and alter its time instead of running a new effect. There could also be an option for the maximum possible time.

This would work well with the gradual curse, and fix issues with some effects like hallucinations, which sound very ackward when they stack up from a quick ascent.

**Comment by lizelive** [comment]
is this reopened to allow for config of which curses can stack?

**Comment by 0ffz** [comment]
This idea is a little convoluted right now, closing since I think this was mostly meant for effect stacking which we do now anyways.
