### ISSUE TITLE
Maximum health decrease curse effect

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/MineInAbyss#32]
An effect that would temporarily decrease the maximum health. It appears this can't be done with potion effects anymore, but it looks like there are spigot methods for it.

**Comment by Paul1365972** [comment]
Something along the lines of
```
void applyEffect(Player player) {
    AttributeModifier modifier = new AttributeModifier(UUID, "Curse Health Debuff", -strength, AttributeModifier.Operation.ADD_NUMBER);
    player.getAttribute(Attribute.GENERIC_MAX_HEALTH).addModifier(modifier);
}

public void cleanUp(Player player) {
    player.getAttribute(Attribute.GENERIC_MAX_HEALTH).getModifiers().removeIf(m -> UUID.equals(m.getUniqueId()));
}
```

**Comment by 0ffz** [comment]
That looks good. Feel free to start working on that, I could assign the issue to you if you're unable to assign yourself.

**Comment by Paul1365972** [comment]
To implement this in a safe and robust way I would rewrite the curse system as a separate plugin, while trying to keep as much the same as possible, if that's fine with @Derongan
