### ISSUE TITLE
Hub item storage

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/MineInAbyss#63]
We'd like a way for players to store items in Orth for adventure server. In the future they will be able to have housing to place items into, but for now we need to keep things simple, so I'd like something similar to an ender chest for now.

Requirements:
- Players are able to run a command that opens their ender chest only when in the hub section (as defined in config)
- An extension function `Player.openHubStorage()` which will also open this menu up for them. Call this function when the command is run. In the future we might have a character to interact with that opens the menu.

**Comment by venikman1** [comment]
I want to do it.

**Comment by venikman1** [comment]
https://github.com/MineInAbyss/MineInAbyss/pull/64
