### ISSUE TITLE
Upgrade old components for new Geary

### ISSUE THREAD

**Issue by Derongan** [MineInAbyss/MineInAbyss#67]
Failing on https://github.com/MineInAbyss/MineInAbyss/commit/aa5bf92d6fd8d06a3c1ec2441d8ae5d0d6dae546. Geary must have updated version.

We need to have a more robust way of handling our dependencies. If there was an actual breaking change, we should up the geary version #

**Comment by 0ffz** [comment]
Yeah agreed I've been a little inconsistent with the version changes, plan to do better now that I'm not directly working off the master branches.

**Comment by 0ffz** [comment]
Oh actually the issues here are from us using the old geary dependency when it doesn't exist anymore. I've started rewriting the depth meter into the new system and planning to commit that soon enough, just had to work on mob spawns first.
