### ISSUE TITLE
PVP selector when starting dive

### ISSUE THREAD

**Issue by 0ffz** [MineInAbyss/MineInAbyss#69]
When going into the abyss players should get a chat popup would be better popup that asks them whether they want pvp on or off for the run. Players may click in chat to turn it on or off. Once a choice has been made it is finalized for that run.

If the player doesn't make a choice within going down one section, the last selected option is used.

**Comment by PLPERR** [comment]
Would it not be easier to simply ask them if they want PvP on or off when they go to L1S1 or come back to Orth? That way when you start your descent, you cant change it unless you come back all the way up.

**Comment by Boy0000** [comment]
Yeah thats the idea. When you enter the Abyss you are asked. If you don't answer it will default to the last selected one

**Comment by PLPERR** [comment]
Gonna try my hand at it when everything will be setup.
