### ISSUE TITLE
ECS Curse

### ISSUE THREAD

**Issue by Boy0000** [MineInAbyss/MineInAbyss#71]
A feature that gets a list of all the registered curse effects for a specified layer. A lot of relics are gonna apply "The Curse" to players or entities so would be easier if this was a thing instead of manually specifying them.

**Comment by 0ffz** [comment]
We could add an action that applies the curse effect of a layer by name or location.

While we're at it, could also rewrite the curse in our ECS, it really wouldn't be hard.

**Comment by Boy0000** [comment]
Honestly having the option of both the location of the player or specifying a name would be cool. Some relics will use a specified layer all the time, whilst some could just take the curse of the current location i suppoose

**Comment by 0ffz** [comment]
Closing so we can properly organize as a curse revamp project in the future.
